# -*- mode: ruby -*-
# vi: set ft=ruby :

# Version: v1.0.0
# Created by: Nick Kjolsing
# Date written: 09/30/2021
# Course: INET 4031
# Lab: 6

# Vagrant do loop start
Vagrant.configure("2") do |config|
   config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "2048"
      vb.cpus = "2"
      end
   config.vm.box = "ubuntu/bionic64"
   # Port Forwarding for Apache Server
   config.vm.network "forwarded_port", guest: 80, host: 80

   # Shell commands for installing packages
   config.vm.provision "shell", inline: <<-SHELL
   apt update
   apt install -y apache2
   apt install -y mariadb-server
   apt install mysql-server
   apt install -y php libapache2-mod-php php-mysql
   SHELL
  
   # Copy local file to Vagrant instance
   config.vm.provision "file", source: "./users.sql", destination: "users.sql"

  end
  